apiVersion: v1
kind: Service
metadata:
  name: helloworld-app-service
  annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  selector:
    app: helloworld
  type: LoadBalancer
  ports:
   -  name: http
      nodePort: 30081
      protocol: TCP
      port: 8081
      targetPort: 8081
