apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-managed-eks-cluster
  region: eu-west-1
  version: "1.18"

vpc:
  id: "vpc-45b4573c"
  subnets:
    private:
      eu-west-1a: 
        id: subnet-96d28ff0 
      eu-west-1b: 
        id: subnet-7a0d2132
      eu-west-1c: 
        id: subnet-1788164d

managedNodeGroups:
  - name: managed-ng-1-workers
    instanceType: t2.micro
    desiredCapacity: 3
    volumeSize: 20
    privateNetworking: true


  - name: managed-ng-2-workers
    instanceType: t2.micro
    desiredCapacity: 3
    volumeSize: 20
    privateNetworking: true

cloudWatch:
  clusterLogging:
    enableTypes:
      - "api"
      - "audit"
      - "authenticator"
      - "controllerManager"
      - "scheduler"
